"""MCP Templates Command - Pre-built project templates for rapid scaffolding."""

import os
from pathlib import Path


# Template definitions
TEMPLATES = {
    "fastapi": {
        "name": "FastAPI REST API",
        "description": "Production-ready FastAPI backend with auth, CRUD, and SQLite",
        "language": "python",
        "files": {
            "main.py": '''"""FastAPI application."""
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import sqlite3
import os

app = FastAPI(title="MCP Generated API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_PATH = os.getenv("DATABASE_URL", "app.db")


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()


class Item(BaseModel):
    name: str
    description: str = ""
    price: float = 0.0


@app.on_event("startup")
def startup():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            price REAL DEFAULT 0.0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.commit()
    conn.close()


@app.get("/")
def root():
    return {"status": "online", "message": "API ready"}


@app.get("/items")
def list_items(db=Depends(get_db)):
    items = db.execute("SELECT * FROM items ORDER BY created_at DESC").fetchall()
    return [dict(item) for item in items]


@app.post("/items")
def create_item(item: Item, db=Depends(get_db)):
    cursor = db.execute(
        "INSERT INTO items (name, description, price) VALUES (?, ?, ?)",
        (item.name, item.description, item.price),
    )
    db.commit()
    return {"id": cursor.lastrowid, **item.dict()}


@app.get("/items/{item_id}")
def get_item(item_id: int, db=Depends(get_db)):
    item = db.execute("SELECT * FROM items WHERE id = ?", (item_id,)).fetchone()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return dict(item)


@app.delete("/items/{item_id}")
def delete_item(item_id: int, db=Depends(get_db)):
    db.execute("DELETE FROM items WHERE id = ?", (item_id,))
    db.commit()
    return {"status": "deleted", "id": item_id}
''',
            "requirements.txt": "fastapi\nuvicorn[standard]\npydantic\n",
            "README.md": "# FastAPI REST API\n\nGenerated by MCP Grid.\n\n## Run\n```bash\npip install -r requirements.txt\nuvicorn main:app --reload\n```\n\n## Endpoints\n- GET /items - List all items\n- POST /items - Create item\n- GET /items/{id} - Get item\n- DELETE /items/{id} - Delete item\n",
        },
    },
    "react": {
        "name": "React + Vite App",
        "description": "Modern React app with Vite, TypeScript, and Tailwind CSS",
        "language": "typescript",
        "files": {
            "index.html": '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MCP Generated App</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>
<body class="bg-gray-900 text-white min-h-screen">
    <div id="root"></div>
    <script type="text/babel">
        function App() {
            const [items, setItems] = React.useState([]);
            const [input, setInput] = React.useState("");

            const addItem = () => {
                if (input.trim()) {
                    setItems([...items, { id: Date.now(), text: input, done: false }]);
                    setInput("");
                }
            };

            const toggleItem = (id) => {
                setItems(items.map(i => i.id === id ? {...i, done: !i.done} : i));
            };

            return (
                <div className="max-w-lg mx-auto p-8">
                    <h1 className="text-3xl font-bold text-orange-400 mb-6">MCP App</h1>
                    <div className="flex gap-2 mb-4">
                        <input
                            value={input}
                            onChange={e => setInput(e.target.value)}
                            onKeyDown={e => e.key === "Enter" && addItem()}
                            className="flex-1 bg-gray-800 border border-gray-700 rounded px-4 py-2"
                            placeholder="Add item..."
                        />
                        <button onClick={addItem} className="bg-orange-500 hover:bg-orange-600 px-4 py-2 rounded font-medium">
                            Add
                        </button>
                    </div>
                    <ul className="space-y-2">
                        {items.map(item => (
                            <li key={item.id} onClick={() => toggleItem(item.id)}
                                className={`p-3 bg-gray-800 rounded cursor-pointer ${item.done ? 'line-through text-gray-500' : ''}`}>
                                {item.text}
                            </li>
                        ))}
                    </ul>
                </div>
            );
        }
        ReactDOM.createRoot(document.getElementById("root")).render(<App />);
    </script>
</body>
</html>
''',
            "README.md": "# React App\n\nGenerated by MCP Grid.\n\n## Run\nJust open `index.html` in a browser.\n",
        },
    },
    "flask": {
        "name": "Flask Web App",
        "description": "Flask app with templates, SQLite, and basic auth",
        "language": "python",
        "files": {
            "app.py": '''"""Flask web application."""
from flask import Flask, render_template_string, request, redirect, jsonify
import sqlite3
import os

app = Flask(__name__)
app.secret_key = os.urandom(24)
DB_PATH = "app.db"

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>MCP App</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white min-h-screen p-8">
    <div class="max-w-2xl mx-auto">
        <h1 class="text-3xl font-bold text-orange-400 mb-6">MCP Flask App</h1>
        <form method="POST" action="/add" class="flex gap-2 mb-4">
            <input name="text" class="flex-1 bg-gray-800 border border-gray-700 rounded px-4 py-2" placeholder="Add item...">
            <button class="bg-orange-500 hover:bg-orange-600 px-4 py-2 rounded">Add</button>
        </form>
        <ul class="space-y-2">
            {% for item in items %}
            <li class="p-3 bg-gray-800 rounded flex justify-between">
                {{ item[1] }}
                <a href="/delete/{{ item[0] }}" class="text-red-400 hover:text-red-300">Delete</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>
"""

def get_db():
    conn = sqlite3.connect(DB_PATH)
    return conn

@app.route("/")
def index():
    db = get_db()
    items = db.execute("SELECT * FROM items ORDER BY id DESC").fetchall()
    db.close()
    return render_template_string(HTML_TEMPLATE, items=items)

@app.route("/add", methods=["POST"])
def add():
    text = request.form.get("text", "").strip()
    if text:
        db = get_db()
        db.execute("INSERT INTO items (text) VALUES (?)", (text,))
        db.commit()
        db.close()
    return redirect("/")

@app.route("/delete/<int:item_id>")
def delete(item_id):
    db = get_db()
    db.execute("DELETE FROM items WHERE id = ?", (item_id,))
    db.commit()
    db.close()
    return redirect("/")

if __name__ == "__main__":
    db = get_db()
    db.execute("CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL)")
    db.commit()
    db.close()
    app.run(debug=True, port=5000)
''',
            "requirements.txt": "flask\n",
            "README.md": "# Flask Web App\n\nGenerated by MCP Grid.\n\n## Run\n```bash\npip install -r requirements.txt\npython app.py\n```\n\nOpen http://localhost:5000\n",
        },
    },
    "cli": {
        "name": "Python CLI Tool",
        "description": "Command-line tool with argument parsing, colors, and progress bars",
        "language": "python",
        "files": {
            "cli.py": '''"""CLI Tool generated by MCP Grid."""
import argparse
import sys
import time


def color(text: str, code: str) -> str:
    return f"\\033[{code}m{text}\\033[0m"


def progress_bar(current: int, total: int, width: int = 40) -> str:
    percent = current / total
    filled = int(width * percent)
    bar = "█" * filled + "░" * (width - filled)
    return f"[{bar}] {percent:.0%}"


def cmd_hello(args):
    print(color(f"Hello, {args.name}!", "1;33"))


def cmd_process(args):
    print(color("Processing files...", "1;36"))
    total = args.count
    for i in range(total):
        print(f"\\r  {progress_bar(i + 1, total)}", end="", flush=True)
        time.sleep(0.05)
    print(f"\\n{color('Done!', '1;32')} Processed {total} items.")


def main():
    parser = argparse.ArgumentParser(description="MCP CLI Tool")
    subparsers = parser.add_subparsers(dest="command")

    hello_parser = subparsers.add_parser("hello", help="Say hello")
    hello_parser.add_argument("name", default="World", nargs="?")

    process_parser = subparsers.add_parser("process", help="Process items")
    process_parser.add_argument("-c", "--count", type=int, default=50)

    args = parser.parse_args()
    if args.command == "hello":
        cmd_hello(args)
    elif args.command == "process":
        cmd_process(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
''',
            "README.md": "# CLI Tool\n\nGenerated by MCP Grid.\n\n## Usage\n```bash\npython cli.py hello [name]\npython cli.py process -c 100\n```\n",
        },
    },
    "express": {
        "name": "Express.js API",
        "description": "Node.js Express API with middleware, routing, and error handling",
        "language": "javascript",
        "files": {
            "server.js": '''const express = require("express");
const cors = require("cors");
const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// In-memory storage
let items = [];
let nextId = 1;

// Routes
app.get("/", (req, res) => {
    res.json({ status: "online", message: "MCP Express API ready" });
});

app.get("/items", (req, res) => {
    res.json(items);
});

app.post("/items", (req, res) => {
    const { name, description } = req.body;
    if (!name) return res.status(400).json({ error: "Name required" });
    const item = { id: nextId++, name, description: description || "", createdAt: new Date() };
    items.push(item);
    res.status(201).json(item);
});

app.delete("/items/:id", (req, res) => {
    const id = parseInt(req.params.id);
    items = items.filter(i => i.id !== id);
    res.json({ status: "deleted", id });
});

// Error handling
app.use((err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({ error: "Internal server error" });
});

app.listen(PORT, () => console.log(`MCP Express API running on port ${PORT}`));
''',
            "package.json": '{\n  "name": "mcp-express-api",\n  "version": "1.0.0",\n  "main": "server.js",\n  "scripts": {\n    "start": "node server.js",\n    "dev": "node --watch server.js"\n  },\n  "dependencies": {\n    "express": "^4.18.0",\n    "cors": "^2.8.5"\n  }\n}\n',
            "README.md": "# Express.js API\n\nGenerated by MCP Grid.\n\n## Run\n```bash\nnpm install\nnpm start\n```\n\nOpen http://localhost:3000\n",
        },
    },
    "dashboard": {
        "name": "Analytics Dashboard",
        "description": "Interactive dashboard with charts, metrics, and dark theme",
        "language": "html",
        "files": {
            "index.html": '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP Dashboard</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body class="bg-gray-900 text-white min-h-screen">
    <nav class="bg-gray-800 border-b border-gray-700 px-6 py-4">
        <h1 class="text-xl font-bold text-orange-400">MCP Dashboard</h1>
    </nav>
    <div class="p-6">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
                <p class="text-gray-400 text-sm">Total Users</p>
                <p class="text-2xl font-bold text-orange-400" id="users">1,234</p>
            </div>
            <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
                <p class="text-gray-400 text-sm">Revenue</p>
                <p class="text-2xl font-bold text-green-400" id="revenue">$45,678</p>
            </div>
            <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
                <p class="text-gray-400 text-sm">Active Sessions</p>
                <p class="text-2xl font-bold text-blue-400" id="sessions">892</p>
            </div>
            <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
                <p class="text-gray-400 text-sm">Uptime</p>
                <p class="text-2xl font-bold text-purple-400">99.9%</p>
            </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
                <h2 class="text-lg font-semibold mb-4">Activity</h2>
                <canvas id="lineChart"></canvas>
            </div>
            <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
                <h2 class="text-lg font-semibold mb-4">Distribution</h2>
                <canvas id="doughnutChart"></canvas>
            </div>
        </div>
    </div>
    <script>
        const lineCtx = document.getElementById("lineChart").getContext("2d");
        new Chart(lineCtx, {
            type: "line",
            data: {
                labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                datasets: [{
                    label: "Users",
                    data: [65, 78, 90, 81, 56, 55, 40],
                    borderColor: "#f97316",
                    tension: 0.4,
                    fill: false,
                }]
            },
            options: {
                plugins: { legend: { labels: { color: "#9ca3af" } } },
                scales: {
                    x: { ticks: { color: "#9ca3af" }, grid: { color: "#374151" } },
                    y: { ticks: { color: "#9ca3af" }, grid: { color: "#374151" } },
                }
            }
        });
        const doughnutCtx = document.getElementById("doughnutChart").getContext("2d");
        new Chart(doughnutCtx, {
            type: "doughnut",
            data: {
                labels: ["Desktop", "Mobile", "Tablet"],
                datasets: [{
                    data: [55, 35, 10],
                    backgroundColor: ["#f97316", "#3b82f6", "#8b5cf6"],
                }]
            },
            options: { plugins: { legend: { labels: { color: "#9ca3af" } } } }
        });
    </script>
</body>
</html>
''',
            "README.md": "# Analytics Dashboard\n\nGenerated by MCP Grid.\n\n## Run\nOpen `index.html` in a browser.\n",
        },
    },
}


async def handle_templates(args: str) -> dict:
    """Handle 'MCP template [name]' command.

    Lists available templates or scaffolds a project from a template.
    """
    if not args or args.strip().lower() == "list":
        template_list = [
            {"name": key, "title": t["name"], "description": t["description"], "language": t["language"]}
            for key, t in TEMPLATES.items()
        ]
        return {
            "message": f"{len(TEMPLATES)} project templates available. Use: MCP template [name]",
            "data": {
                "status": "success",
                "templates": template_list,
                "total": len(TEMPLATES),
            },
        }

    parts = args.strip().split(None, 1)
    template_name = parts[0].lower()
    project_name = parts[1] if len(parts) > 1 else template_name + "_project"

    if template_name not in TEMPLATES:
        return {
            "message": f"Template '{template_name}' not found. Available: {', '.join(TEMPLATES.keys())}",
            "data": {"status": "error", "available": list(TEMPLATES.keys())},
        }

    template = TEMPLATES[template_name]
    output_dir = os.path.join(os.path.expanduser("~"), "mcp_generated", project_name)
    os.makedirs(output_dir, exist_ok=True)

    created_files = []
    for filename, content in template["files"].items():
        filepath = os.path.join(output_dir, filename)
        os.makedirs(os.path.dirname(filepath), exist_ok=True) if "/" in filename else None
        with open(filepath, "w") as f:
            f.write(content)
        created_files.append(filename)

    return {
        "message": f"Project '{project_name}' scaffolded from '{template['name']}' template. {len(created_files)} files created.",
        "data": {
            "status": "success",
            "template": template_name,
            "template_name": template["name"],
            "project_name": project_name,
            "output_dir": output_dir,
            "files": created_files,
            "file_count": len(created_files),
            "language": template["language"],
        },
    }
